[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "echo '=== محتوى /app ===' && ls -la /app && echo '=== محتوى cwd ===' && ls -la && echo '=== ملفات py ===' && find / -name 'lastv.py' 2>/dev/null && sleep 5 && streamlit run /app/lastv.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false"