[phases.setup]
nixPkgs = ["python311Full", "gcc"]

[phases.install]
cmds = [
    "python3.11 -m ensurepip --upgrade",
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install -r requirements.txt"
]
[start]
cmd = "cd /app && streamlit run /app/Lastv.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false"